var jsonstring = {
  "regions": [
    "Auckland",
    "Bay of Plenty",
    "Canterbury",
    "East Coast",
    "Hawkes Bay",
    "Manawatu",
    "Marlborough",
    "Nelson/Tasman",
    "Northland",
    "Otago",
    "South Canterbury",
    "Southland",
    "Taranaki",
    "Waikato",
    "Wairarapa",
    "Wanganui",
    "Wellington",
    "West Coast"
  ],
  "districts": {
    "Auckland": [
      [
        "Auckland City"
      ],
      [
        "Franklin"
      ],
      [
        "Manukau City"
      ],
      [
        "North Shore City"
      ],
      [
        "Papakura"
      ],
      [
        "Rodney"
      ],
      [
        "Waiheke Island"
      ],
      [
        "Waitakere"
      ]
    ],
    "Bay of Plenty": [
      [
        "Kawerau"
      ],
      [
        "Opotiki"
      ],
      [
        "Rotorua"
      ],
      [
        "Tauranga"
      ],
      [
        "Western Bay Of Plenty"
      ],
      [
        "Whakatane"
      ]
    ],
    "Canterbury": [
      [
        "Amberley"
      ],
      [
        "Ashburton"
      ],
      [
        "Banks Peninsula"
      ],
      [
        "Cheviot"
      ],
      [
        "Christchurch City"
      ],
      [
        "Culverden"
      ],
      [
        "Hurunui"
      ],
      [
        "Kaikoura"
      ],
      [
        "Kainga"
      ],
      [
        "Selwyn"
      ],
      [
        "Waimakariri"
      ]
    ],
    "East Coast": [
      [
        "Gisborne"
      ],
      [
        "Hicks Bay"
      ],
      [
        "Matawai"
      ]
    ],
    "Hawkes Bay": [
      [
        "Central Hawkes Bay"
      ],
      [
        "Hastings"
      ],
      [
        "Napier"
      ],
      [
        "Wairoa"
      ]
    ],
    "Manawatu": [
      [
        "Horowhenua"
      ],
      [
        "Levin"
      ],
      [
        "Manawatu"
      ],
      [
        "Palmerston North"
      ],
      [
        "Rangitikei"
      ],
      [
        "Tararua"
      ]
    ],
    "Marlborough": [
      [
        "Kaikoura"
      ],
      [
        "Marlborough"
      ]
    ],
    "Nelson/Tasman": [
      [
        "Motueka"
      ],
      [
        "Nelson"
      ],
      [
        "Tasman"
      ]
    ],
    "Northland": [
      [
        "Dargaville"
      ],
      [
        "Far North"
      ],
      [
        "Herekino"
      ],
      [
        "Kaikohe"
      ],
      [
        "Kaipara"
      ],
      [
        "Kaitaia"
      ],
      [
        "Kerikeri"
      ],
      [
        "Moerewa"
      ],
      [
        "Paihia"
      ],
      [
        "Russell"
      ],
      [
        "Whangarei"
      ]
    ],
    "Otago": [
      [
        "Alexandra"
      ],
      [
        "Central Otago"
      ],
      [
        "Clutha"
      ],
      [
        "Dunedin"
      ],
      [
        "Oamaru"
      ],
      [
        "Queenstown-Lakes"
      ],
      [
        "Waitaki"
      ]
    ],
    "South Canterbury": [
      [
        "Fairlie"
      ],
      [
        "Geraldine"
      ],
      [
        "Mackenzie"
      ],
      [
        "Temuka"
      ],
      [
        "Timaru"
      ],
      [
        "Waimate"
      ]
    ],
    "Southland": [
      [
        "Catlins"
      ],
      [
        "Gore"
      ],
      [
        "Invercargill"
      ],
      [
        "Southland"
      ],
      [
        "Winton"
      ]
    ],
    "Taranaki": [
      [
        "New Plymouth"
      ],
      [
        "South Taranaki"
      ],
      [
        "Stratford"
      ]
    ],
    "Waikato": [
      [
        "Hamilton"
      ],
      [
        "Hauraki"
      ],
      [
        "Matamata-Piako"
      ],
      [
        "Morrinsville"
      ],
      [
        "Otorohanga"
      ],
      [
        "South Waikato"
      ],
      [
        "Taupo"
      ],
      [
        "Thames-Coromandel"
      ],
      [
        "Waikato"
      ],
      [
        "Waimate"
      ],
      [
        "Waipa"
      ],
      [
        "Waitomo"
      ]
    ],
    "Wairarapa": [
      [
        "Wairarapa"
      ]
    ],
    "Wanganui": [
      [
        "Ruapehu"
      ],
      [
        "Wanganui"
      ]
    ],
    "Wellington": [
      [
        "Kapiti Coast"
      ],
      [
        "Lower Hutt"
      ],
      [
        "Porirua"
      ],
      [
        "Upper Hutt"
      ],
      [
        "Wellington"
      ]
    ],
    "West Coast": [
      [
        "Buller"
      ],
      [
        "Grey"
      ],
      [
        "Westland"
      ]
    ]
  },
  "suburbs": {
    "Auckland": {
      "Auckland City": [
        "Arch Hill",
        "Auckland City",
        "Avondale",
        "Balmoral",
        "Blockhouse Bay",
        "Coxs Bay",
        "Eden Terrace",
        "Ellerslie",
        "Epsom",
        "Freemans Bay",
        "Glen Innes",
        "Glendowie",
        "Grafton",
        "Great Barrier Island",
        "Green Lane",
        "Grey Lynn",
        "Herne Bay",
        "Hillsborough",
        "Kingsland",
        "Kohimarama",
        "Lynfield",
        "Meadowbank",
        "Mission Bay",
        "Morningside",
        "Mount Albert",
        "Mount Eden",
        "Mount Roskill",
        "Mount Wellington",
        "New Windsor",
        "Newmarket",
        "Newton",
        "One Tree Hill",
        "Onehunga",
        "Orakei",
        "Oranga",
        "Otahuhu",
        "Owairaka",
        "Panmure",
        "Parnell",
        "Penrose",
        "Point Chevalier",
        "Point England",
        "Ponsonby",
        "Rakino Island",
        "Remuera",
        "Royal Oak",
        "Saint Heliers",
        "Saint Johns",
        "Saint Johns Park",
        "Saint Lukes",
        "Saint Marys Bay",
        "Sandringham",
        "Tamaki",
        "Te Papapa",
        "Three Kings",
        "Wai O Taiki Bay",
        "Waiheke Island",
        "Waikowhai",
        "Waterview",
        "Wesley",
        "Westmere"
      ],
      "Franklin": [
        "Aka Aka",
        "Ararimu",
        "Awhitu",
        "Bombay",
        "Buckland",
        "Clarks Beach",
        "Glenbrook",
        "Harrisville",
        "Helvetia",
        "Hunua",
        "Kaiaua",
        "Karaka",
        "Kingseat",
        "Mangatangi",
        "Mangatawhiri",
        "Maramarua",
        "Mauku",
        "Mercer",
        "Onewhero",
        "Otaua",
        "Paparimu",
        "Patumahoe",
        "Pokeno",
        "Port Waikato",
        "Pukekawa",
        "Pukekohe",
        "Pukekohe East",
        "Puni",
        "Ramarama",
        "Taurangaruru",
        "Te Kohanga",
        "Tuakau",
        "Waiau Pa",
        "Waiuku",
        "Wharekawa"
      ],
      "Manukau City": [
        "Alfriston",
        "Beachlands",
        "Botany Downs",
        "Brookby",
        "Bucklands Beach",
        "Burswood",
        "Chapel Downs",
        "Clendon Park",
        "Clevedon",
        "Clover Park",
        "Cockle Bay",
        "Cumbria Downs",
        "Dannemora",
        "East Tamaki",
        "Eastern Beach",
        "Farm Cove",
        "Favona",
        "Flat Bush",
        "Golflands",
        "Goodwood Heights",
        "Greenmount",
        "Half Moon Bay",
        "Highland Park",
        "Hill Park",
        "Homai",
        "Howick",
        "Huntington Park",
        "Kawakawa Bay",
        "Mahia Park",
        "Mangere",
        "Mangere Bridge",
        "Mangere East",
        "Manukau",
        "Manukau Heights",
        "Manurewa",
        "Maraetai",
        "Matingarahi",
        "Mellons Bay",
        "Northpark",
        "Omana Beach",
        "Orere",
        "Orere Point",
        "Otara",
        "Pakuranga",
        "Papatoetoe",
        "Point View Park",
        "Puhinui",
        "Randwick Park",
        "Shelly Park",
        "Somerville",
        "Sunnyhills",
        "The Gardens",
        "Totara Heights",
        "Wattle Downs",
        "Weymouth",
        "Whitford",
        "Wiri"
      ],
      "North Shore City": [
        "Albany",
        "Bayswater",
        "Bayview",
        "Beach Haven",
        "Belmont",
        "Birkdale",
        "Birkenhead",
        "Browns Bay",
        "Campbells Bay",
        "Castor Bay",
        "Chatswood",
        "Cheltenham",
        "Chester Park",
        "Crown Hill",
        "Devonport",
        "Forrest Hill",
        "Glenfield",
        "Greenhithe",
        "Hauraki",
        "Hillcrest",
        "Long Bay",
        "Mairangi Bay",
        "Marlborough",
        "Meadowood",
        "Milford",
        "Murrays Bay",
        "Narrow Neck",
        "North Harbour",
        "Northcote",
        "Northcote Point",
        "Northcross",
        "Okura",
        "Oteha",
        "Paremoremo",
        "Pinehill",
        "Rothesay Bay",
        "Schnapper Rock",
        "Stanley Bay",
        "Sunnybrae",
        "Sunnynook",
        "Takapuna",
        "The Palms",
        "Torbay",
        "Totaravale",
        "Unsworth Heights",
        "Waiake",
        "Wainoni",
        "Wairau Park",
        "Westlake",
        "Windsor Park"
      ],
      "Papakura": [
        "Ardmore",
        "Conifer Grove",
        "Drury",
        "Opaheke",
        "Pahurehure",
        "Papakura",
        "Red Hill",
        "Takanini"
      ],
      "Rodney": [
        "Ahuroa",
        "Albany Heights",
        "Algies Bay",
        "Arkles Bay",
        "Army Bay",
        "Big Manly",
        "Coatesville",
        "Dairy Flat",
        "Gulf Harbour",
        "Hatfields Beach",
        "Helensville",
        "Hobbs Bay",
        "Hoteo",
        "Huapai",
        "Kaipara Flats",
        "Kaukapakapa",
        "Kawau Island",
        "Kumeu",
        "Leigh",
        "Little Manly",
        "Mahurangi",
        "Makarau",
        "Manly",
        "Matakana",
        "Matakatia Bay",
        "Maygrove",
        "Muriwai Beach",
        "Muriwai Valley",
        "Omaha",
        "Omaha Flats",
        "Orewa",
        "Parakai",
        "Parkhurst",
        "Point Wells",
        "Puhoi",
        "Red Beach",
        "Redvale",
        "Riverhead",
        "Sandspit",
        "Silverdale",
        "Snells Beach",
        "South Head",
        "Stanmore Bay",
        "Stillwater",
        "Streamlands",
        "Tapora",
        "Tauhoa",
        "Taupaki",
        "Tawharanui Peninsula",
        "Te Arai",
        "Te Hana",
        "The Grange",
        "Ti Point",
        "Tindalls Beach",
        "Tomarata",
        "Wade Heads",
        "Waikoukou Valley",
        "Waimauku",
        "Waitakere",
        "Waitoki",
        "Waiwera",
        "Warkworth",
        "Wellsford",
        "Whangaparaoa",
        "Whangateau",
        "Woodcocks"
      ],
      "Waiheke Island": [
        "Awaawaroa",
        "Blackpool",
        "Church Bay",
        "Connells Bay",
        "Cowes Bay",
        "Enclosure Bay",
        "Hekerua Bay",
        "Kennedy Point",
        "Little Oneroa",
        "Matiatia Bay",
        "Omiha",
        "Oneroa",
        "Onetangi",
        "Orapiu",
        "Ostend",
        "Palm Beach",
        "Sandy Bay",
        "Surfdale",
        "Te Whau Bay",
        "Woodside Bay"
      ],
      "Waitakere": [
        "Anawhata",
        "Bethells Beach ( Te Henga)",
        "Cornwallis",
        "French Bay",
        "Glen Eden",
        "Glendene",
        "Green Bay",
        "Harbour View",
        "Henderson",
        "Henderson Valley",
        "Herald Island",
        "Hobsonville",
        "Huia",
        "Karekare",
        "Kelston",
        "Laingholm",
        "Lincoln",
        "Little Huia",
        "Massey",
        "Massey East",
        "Massey West",
        "Mclaren Park",
        "New Lynn",
        "Oratia",
        "Palm Heights",
        "Piha",
        "Ranui",
        "Sunnyvale",
        "Swanson",
        "Te Atatu Peninsula",
        "Te Atatu South",
        "Titirangi",
        "Waiatarua",
        "Waimanu Bay",
        "West Harbour",
        "Western Heights",
        "Western Springs",
        "Whatipu",
        "Whenuapai",
        "Wood Bay",
        "Woodlands Park"
      ]
    },
    "Bay of Plenty": {
      "Kawerau": [
        "Kawerau"
      ],
      "Opotiki": [
        "Awanui",
        "Hospital Hill",
        "Kutarere",
        "Opotiki"
      ],
      "Rotorua": [
        "Atiamuri",
        "Awahou",
        "Fairy Springs",
        "Fenton Park",
        "Fordlands",
        "Glenholme",
        "Golden Springs",
        "Hamurana",
        "Hannahs Bay",
        "Holdens Bay",
        "Horohoro",
        "Kaharoa",
        "Kawaha Point",
        "Koutu",
        "Lake Okareka",
        "Lake Tarawera",
        "Lynmore",
        "Mamaku",
        "Mangakakahi",
        "Ngongotaha",
        "Okere Falls",
        "Owhata",
        "Pukehangi",
        "Reporoa",
        "Rerewhakaaitu",
        "Rotorua",
        "Springfield",
        "Te Ngae",
        "Tikitere",
        "Victoria",
        "Westbrook",
        "Western Heights"
      ],
      "Tauranga": [
        "Arataki",
        "Avenues",
        "Bayfair",
        "Bellevue",
        "Bethlehem",
        "Brookfield",
        "Bureta",
        "Cambridge Heights",
        "Gate Pa",
        "Greerton",
        "Hairini",
        "Judea",
        "Kairua",
        "Matua",
        "Maungatapu",
        "Mount Maunganui",
        "Ohauiti",
        "Omanu",
        "Otumoetai",
        "Papamoa",
        "Papamoa Beach",
        "Parkvale",
        "Poike",
        "Tauranga Central",
        "Tauranga South",
        "Tauriko",
        "Te Maunga",
        "Welcome Bay"
      ],
      "Western Bay Of Plenty": [
        "Aongatete",
        "Bowentown",
        "Katikati",
        "Lower Kaimai",
        "Maketu",
        "Omokoroa",
        "Oropi",
        "Paengaroa",
        "Pukehina",
        "Pyes Pa",
        "Rangiuru",
        "Te Puke",
        "Te Puna",
        "Waihi Beach",
        "Whakamarama"
      ],
      "Whakatane": [
        "Awakaponga",
        "Awakeri",
        "Coastlands",
        "Edgecumbe",
        "Galatea",
        "Matata",
        "Murupara",
        "Ohope",
        "Onepu",
        "Otakiri",
        "Pahou",
        "Paroa",
        "Poroporo",
        "Port Ohope",
        "Ruatoki North",
        "Taneatua",
        "Te Teko",
        "Thornton",
        "Waimana",
        "Whakatane"
      ]
    },
    "Canterbury": {
      "Amberley": [
        "Ashley Forest",
        "Balcairn",
        "Glasnevin"
      ],
      "Ashburton": [
        "Ashburton",
        "Fairton",
        "Hinds",
        "Mayfield",
        "Methven",
        "Mount Somers",
        "Rakaia",
        "Tinwald"
      ],
      "Banks Peninsula": [
        "Akaroa",
        "Barrys Bay",
        "Diamond Harbour",
        "Duvauchelle",
        "Governors Bay",
        "Le Bons Bay",
        "Little Akaloa",
        "Little River",
        "Lyttelton",
        "Takamutua",
        "Wainui"
      ],
      "Cheviot": [
        "Blythe Valley",
        "Caverhill",
        "Domett",
        "Gore Bay",
        "Hurunui Mouth",
        "Mina",
        "Phoebe",
        "Port Robinson"
      ],
      "Christchurch City": [
        "Addington",
        "Aidanfield",
        "Aranui",
        "Avondale",
        "Avonhead",
        "Avonside",
        "Balmoral Hill",
        "Barrington",
        "Beckenham",
        "Belfast",
        "Bexley",
        "Bishopdale",
        "Bromley",
        "Brookhaven",
        "Brookside",
        "Broomfield",
        "Bryndwr",
        "Burnside",
        "Burwood",
        "Casebrook",
        "Cashmere",
        "Chaneys",
        "Christchurch",
        "Clifton",
        "Dallington",
        "Edgeware",
        "Fendalton",
        "Ferrymead",
        "Halswell",
        "Harewood",
        "Heathcote",
        "Hei Hei",
        "Hillmorton",
        "Hillsborough",
        "Hoon Hay",
        "Hornby",
        "Hornby South",
        "Huntsbury",
        "Hyde Park",
        "Ilam",
        "Islington",
        "Kainga",
        "Kowai Bush",
        "Linwood",
        "Lyttleton",
        "Mairehau",
        "Marshland",
        "Masham",
        "Mccormacks Bay",
        "Merivale",
        "Middleton",
        "Moncks Bay",
        "Moncks Spur",
        "Mount Pleasant",
        "Murray Aynsley",
        "New Brighton",
        "North Avon",
        "North Beach",
        "North Linwood",
        "North New Brighton",
        "Northwood",
        "Oaklands",
        "Opawa",
        "Papanui",
        "Parklands",
        "Phillipstown",
        "Queens Park",
        "Rapaki",
        "Redcliffs",
        "Redwood",
        "Riccarton",
        "Richmond",
        "Russley",
        "Saint Albans",
        "Saint Andrews Hill",
        "Saint Martins",
        "Scarborough",
        "Shirley",
        "Sockburn",
        "Somerfield",
        "South New Brighton",
        "Southshore",
        "Spencerville",
        "Spreydon",
        "Strowan",
        "Styx",
        "Sumner",
        "Sydenham",
        "Taitapu",
        "Templeton",
        "Upper Riccarton",
        "Waimairi Beach",
        "Wainoni",
        "Wainui",
        "Waltham",
        "Westlake",
        "Westmorland",
        "Wigram",
        "Wigram Village",
        "Woolston",
        "Yaldhurst"
      ],
      "Culverden": [
        "Mouse Point",
        "Pahau",
        "Red Post Corner"
      ],
      "Hurunui": [
        "Amberley",
        "Amberley Beach",
        "Balmoral",
        "Culverden",
        "Hanmer Springs",
        "Hawarden",
        "Leithfield Beach",
        "Motunau",
        "Waiau",
        "Waikari",
        "Waipara"
      ],
      "Kaikoura": [
        "Goose Bay",
        "Hapuku",
        "Kaikoura",
        "Mangamaunu",
        "Oaro",
        "Peketa",
        "South Bay",
        "Swyncombe"
      ],
      "Kainga": [
        "Brooklands"
      ],
      "Selwyn": [
        "Arthurs Pass",
        "Aylesbury",
        "Burnham",
        "Castle Hill",
        "Charing Cross",
        "Coalgate",
        "Darfield",
        "Doyleston",
        "Dunsandel",
        "Greendale",
        "Homebush",
        "Hororata",
        "Kirwee",
        "Leeston",
        "Lincoln",
        "Norwood",
        "Prebbleton",
        "Rolleston",
        "Sheffield",
        "Southbridge",
        "Springfield",
        "Springston",
        "Tai Tapu",
        "Weedons",
        "West Melton"
      ],
      "Waimakariri": [
        "Ashley",
        "Bexley",
        "Clarkville",
        "Coldstream",
        "Cust",
        "Fernside",
        "Flaxton",
        "Horrellville",
        "Kaiapoi",
        "Leithfield",
        "Loburn",
        "Loburn North",
        "Ohapuku",
        "Ohoka",
        "Okuku",
        "Oxford",
        "Pegasus",
        "Rangiora",
        "Sefton",
        "Southbrook",
        "Summerhill",
        "Swannanoa",
        "Tuahiwi",
        "Waikuku",
        "West Eyreton",
        "White Rock",
        "Woodend"
      ]
    },
    "East Coast": {
      "Gisborne": [
        "Awapuni",
        "Awatere Valley",
        "Elgin",
        "Gisborne",
        "Hexton",
        "Inner Kati",
        "Kaiti",
        "Makaraka",
        "Makauri",
        "Makorori",
        "Mangapapa",
        "Manutuke",
        "Muriwai",
        "Okitu",
        "Outer Kaiti",
        "Patutahi",
        "Pehiri",
        "Riverdale",
        "Ruatoria",
        "Tamarau",
        "Te Hapara",
        "Te Karaka",
        "Tiniroto",
        "Tokomaru Bay",
        "Tolaga Bay",
        "Waingake",
        "Wainui",
        "Whataupoko"
      ],
      "Hicks Bay": [
        "Hicks Bay",
        "Potaka"
      ],
      "Matawai": [
        "Matawai",
        "Otoko",
        "Rakauroa"
      ]
    },
    "Hawkes Bay": {
      "Central Hawkes Bay": [
        "Elsthorpe",
        "Ongaonga",
        "Otane",
        "Porangahau",
        "Takapau",
        "Waipawa",
        "Waipukurau",
        "Wanstead"
      ],
      "Hastings": [
        "Akina",
        "Bridge Pa",
        "Camberley",
        "Clifton",
        "Clive",
        "Crownthorpe",
        "East Clive",
        "Eskdale",
        "Fernhill",
        "Flaxmere",
        "Frimley",
        "Hastings Central",
        "Haumoana",
        "Havelock North",
        "Kahuranaki",
        "Kereru",
        "Longlands",
        "Mahora",
        "Mangatahi",
        "Mangateretere",
        "Maraekakaho",
        "Mayfair",
        "Moteo",
        "Omahu",
        "Otamauri",
        "Pakipaki",
        "Pakowhai",
        "Parkvale",
        "Patangata",
        "Patoka",
        "Poukawa",
        "Puketapu",
        "Puketitiri",
        "Putorino",
        "Raukawa",
        "Raureka",
        "Rissington",
        "Saint Leonards",
        "Sherenden",
        "Tangoio",
        "Te Awanga",
        "Te Hauke",
        "Te Pohue",
        "Tomoana",
        "Tutira",
        "Twyford",
        "Waimarama",
        "Waipatu",
        "Whakatu",
        "Whirinaki",
        "Woolwich"
      ],
      "Napier": [
        "Ahuriri",
        "Awatoto",
        "Bay View",
        "Bluff Hill",
        "Greenmeadows",
        "Hospital Hill",
        "Jervoistown",
        "Maraenui",
        "Marewa",
        "Meeanee",
        "Mission View",
        "Napier",
        "Napier South",
        "Onekawa",
        "Pandora",
        "Pirimai",
        "Poraiti",
        "Rissington",
        "Tamatea",
        "Taradale",
        "Westshore"
      ],
      "Wairoa": [
        "Frasertown",
        "Kotemaori",
        "Mahia Beach",
        "Morere",
        "Wairoa"
      ]
    },
    "Manawatu": {
      "Horowhenua": [
        "Foxton",
        "Foxton Beach",
        "Gladstone",
        "Heatherlea",
        "Hokio Beach",
        "Ihakara",
        "Kuku",
        "Manakau",
        "Muhunoa East",
        "Ohau",
        "Opiki",
        "Shannon",
        "Tokomaru",
        "Waitarere"
      ],
      "Levin": [
        "Koputaroa",
        "Levin Central",
        "Poroutawhao",
        "Waitarere Beach",
        "Weraroa"
      ],
      "Manawatu": [
        "Apiti",
        "Bunnythorpe",
        "Cheltenham",
        "Colyton",
        "Feilding",
        "Halcombe",
        "Himatangi",
        "Hiwinui",
        "Kimbolton",
        "Longburn",
        "Mount Biggs",
        "Newbury",
        "Rongotea",
        "Sanson",
        "Tangimoana"
      ],
      "Palmerston North": [
        "Aokautere",
        "Ashhurst",
        "Awahuri",
        "Awapuni",
        "Cloverlea",
        "Fitzherbert",
        "Highbury",
        "Hokowhitu",
        "Kelvin Grove",
        "Linton",
        "Milson",
        "Palmerston North",
        "Papaioea",
        "Roslyn",
        "Takaro",
        "Terrace End",
        "Tiritea",
        "West End",
        "Westbrook"
      ],
      "Rangitikei": [
        "Bulls",
        "Hunterville",
        "Marton",
        "Taihape",
        "Turakina"
      ],
      "Tararua": [
        "Dannevirke",
        "Eketahuna",
        "Pahiatua",
        "Woodville"
      ]
    },
    "Marlborough": {
      "Kaikoura": [
        "Kekerengu"
      ],
      "Marlborough": [
        "Anakiwa",
        "Awatere Valley",
        "Blenheim",
        "Dashwood",
        "Fairhall",
        "Gladstone",
        "Grovetown",
        "Havelock",
        "Kenepuru Sound",
        "Koromiko",
        "Linkwater",
        "Okaramio",
        "Picton",
        "Portage",
        "Rai Valley",
        "Rapaura",
        "Rarangi",
        "Redwoodtown",
        "Renwick",
        "Riverlands",
        "Seddon",
        "Spring Creek",
        "Tennyson Inlet",
        "Tuamarina",
        "Waihopai Valley",
        "Waikawa",
        "Wairau Valley",
        "Ward",
        "Witherlea",
        "Woodbourne"
      ]
    },
    "Nelson/Tasman": {
      "Motueka": [
        "Port Motueka",
        "Umukuri"
      ],
      "Nelson": [
        "Annesbrook",
        "Atawhai",
        "Bishopdale",
        "Britannia Heights",
        "Brooklands",
        "Cable Bay",
        "Delaware Bay",
        "Dodson Valley",
        "Enner Glynn",
        "Hira",
        "Kokorua",
        "Maitai",
        "Maitai Valley",
        "Maitlands",
        "Marybank",
        "Moana",
        "Monaco",
        "Nayland",
        "Nelson",
        "Nelson East",
        "Nelson South",
        "Ngawhatu",
        "Port Nelson",
        "Rockville",
        "Rotoroa",
        "Stepneyville",
        "Stoke",
        "Tahunanui",
        "The Brook",
        "The Wood",
        "Todds Valley",
        "Toi Toi",
        "Wakatu",
        "Washington Valley"
      ],
      "Tasman": [
        "Aniseed Valley",
        "Brightwater",
        "Brooklyn",
        "Clifton",
        "Collingwood",
        "Hope",
        "Kaiteriteri",
        "Kohatu",
        "Lower Moutere",
        "Mahana",
        "Mapua",
        "Motueka",
        "Motupiko",
        "Murchison",
        "Ngatimoti",
        "Owen River",
        "Patons Rock",
        "Pohara",
        "Richmond",
        "Riwaka",
        "Ruby Bay",
        "Saint Arnaud",
        "Takaka",
        "Tapawera",
        "Upper Moutere",
        "Wakefield"
      ]
    },
    "Northland": {
      "Dargaville": [
        "Arapohue",
        "Baylys Beach",
        "Kaihu",
        "Mamaranui",
        "Parore",
        "Tangowahine",
        "Turiwiri",
        "Waihue"
      ],
      "Far North": [
        "Ahipara",
        "Awanui",
        "Broadwood",
        "Cape Reinga",
        "Coopers Beach",
        "Diggers Valley",
        "Fairburn",
        "Haruru",
        "Henderson Bay",
        "Herekino",
        "Hihi",
        "Horeke",
        "Houhora",
        "Kaeo",
        "Kaimaumau",
        "Karetu",
        "Karikari Pennisula",
        "Kawakawa",
        "Kohukohu",
        "Koutu",
        "Mangonui",
        "Mitimiti",
        "Moerewa",
        "Ohaeawai",
        "Okaihau",
        "Omanaia",
        "Omapere",
        "Opononi",
        "Opua",
        "Oromahoe",
        "Pakaraka",
        "Pamapuria",
        "Panguru",
        "Peria",
        "Pukenui",
        "Rangiahua",
        "Rangiputa",
        "Rawene",
        "Taheke",
        "Taipa",
        "Takahue",
        "Taupo Bay",
        "Tauranga Bay",
        "Te Whau",
        "Tokerau Beach",
        "Totara North",
        "Towai",
        "Victoria Valley",
        "Waimamaku",
        "Waimate North",
        "Waipapa",
        "Waipapakauri",
        "Whangape Harbour",
        "Whangaroa",
        "Whirinaki"
      ],
      "Herekino": [
        "Manukau"
      ],
      "Kaikohe": [
        "Awarua",
        "Mataraua",
        "Ngapipito",
        "Ngapuhi",
        "Ngawha Springs",
        "Punakitere"
      ],
      "Kaipara": [
        "Arapohue",
        "Baylys Beach",
        "Kaiwaka",
        "Kellys Bay",
        "Mangawhai",
        "Mangawhai Heads",
        "Mangawhare",
        "Matakohe",
        "Maungaturoto",
        "Pahi",
        "Paparoa",
        "Pouto",
        "Ruawai",
        "Tangiteroria",
        "Tangowahine",
        "Te Kopuru",
        "Tinopai",
        "Whakapirau"
      ],
      "Kaitaia": [
        "Kaingaroa",
        "Mangatoetoe",
        "Okahu",
        "Oturu",
        "Rangitihi",
        "Ruaroa",
        "Shipwreck Bay"
      ],
      "Kerikeri": [
        "Doves Bay",
        "Kapiro",
        "Kerikeri Inlet",
        "Opito Bay",
        "Pungaere",
        "Purerua",
        "Rangitane",
        "Ranui Gardens",
        "Skudders Beach",
        "Te Tii"
      ],
      "Moerewa": [
        "Matawaia"
      ],
      "Paihia": [
        "Moturoa Island",
        "Okiato Point",
        "Te Haumi",
        "Watea",
        "Whangae Bridge"
      ],
      "Russell": [
        "Dicks Bay",
        "Frenchmans Swamp",
        "Jills Bay",
        "Manawaora",
        "Matauwhi Bay",
        "Okaito",
        "Opunga Cove",
        "Orokawa Bay",
        "Orongo Bay",
        "Parekura Bay",
        "Paroa Bay",
        "Rawhiti",
        "Tapeka Point",
        "Te Hue Bay",
        "Te Wahapu",
        "Waihaha",
        "Waipiro Bay"
      ],
      "Whangarei": [
        "Bream Bay",
        "Central Whangarei",
        "Glenbervie",
        "Hikurangi",
        "Hukerenui",
        "Kamo",
        "Kauri",
        "Kensington",
        "Kokopu",
        "Mairtown",
        "Mangapai",
        "Marsden Point",
        "Marua",
        "Mata",
        "Matapouri",
        "Matarau",
        "Maungakaramea",
        "Maungatapere",
        "Maunu",
        "Mcleod Bay",
        "Morningside",
        "Ngunguru",
        "Oakleigh",
        "Oakura Coast",
        "One Tree Point",
        "Onerahi",
        "Otaika",
        "Otangarei",
        "Parahaki",
        "Parua Bay",
        "Pataua",
        "Pataua North",
        "Pataua South",
        "Port Whangarei",
        "Portland",
        "Raumanga",
        "Regent",
        "Riverside",
        "Ruakaka",
        "Ruatangata",
        "Sherwood Rise",
        "Springs Flat",
        "Tamaterau",
        "Taurikura",
        "Three Mile Bush",
        "Tikipunga",
        "Titoki",
        "Toetoe",
        "Tutukaka",
        "Vinetown",
        "Waikaraka",
        "Waikiekie",
        "Waiotira",
        "Waipu",
        "Waipu Cove",
        "Whananaki",
        "Whangarei",
        "Whangarei Heads",
        "Whangaruru",
        "Whareora",
        "Whatitiri",
        "Whau Valley",
        "Woodhill"
      ]
    },
    "Otago": {
      "Alexandra": [
        "Alexandra",
        "Bridge Hill"
      ],
      "Central Otago": [
        "Clyde",
        "Cromwell",
        "Ettrick",
        "Naseby",
        "Omakau",
        "Oturehua",
        "Ranfurly",
        "Roxburgh",
        "Tarras"
      ],
      "Clutha": [
        "Balclutha",
        "Clifton",
        "Clinton",
        "Kaitangata",
        "Kaka Point",
        "Lawrence",
        "Milton",
        "Owaka",
        "Stirling",
        "Taieri Mouth",
        "Taumata",
        "Waihola",
        "Wairuna"
      ],
      "Dunedin": [
        "Abbotsford",
        "Allanton",
        "Andersons Bay",
        "Aramoana",
        "Balaclava",
        "Belleknowes",
        "Bradford",
        "Brighton",
        "Broad Bay",
        "Brockville",
        "Burnside",
        "Calton Hill",
        "Caversham",
        "Clyde Hill",
        "Company Bay",
        "Concord",
        "Corstorphine",
        "Dalmore",
        "Dunedin City",
        "East Taieri",
        "Fairfield",
        "Glenleith",
        "Glenross",
        "Green Island",
        "Halfway Bush",
        "Harwood",
        "Helensburgh",
        "Heyward Point",
        "Highcliff",
        "Kaikorai",
        "Kaikorai Valley",
        "Karitane",
        "Kenmure",
        "Kensington",
        "Kew",
        "Kinmont Park",
        "Leith Valley",
        "Liberton",
        "Littlebourne",
        "Macandrew Bay",
        "Maori Hill",
        "Maryhill",
        "Maungatua",
        "Middlemarch",
        "Mornington",
        "Mosgiel",
        "Mount Mera",
        "Musselburgh",
        "Normanby",
        "North Dunedin",
        "North East Valley",
        "Ocean Grove",
        "Ocean View",
        "Opoho",
        "Otago Peninsula",
        "Otokia",
        "Outram",
        "Pine Hill",
        "Port Chalmers",
        "Portobello",
        "Ravensbourne",
        "Roseneath",
        "Roslyn",
        "Saddle Hill",
        "Saint Clair",
        "Saint Clair Park",
        "Saint Kilda",
        "Saint Leonards",
        "Sawyers Bay",
        "Scroggs Hill",
        "Shiel Hill",
        "South Dunedin",
        "Tainui",
        "The Cove",
        "Upper Junction",
        "Waikouaiti",
        "Waitati",
        "Wakari",
        "Waldronville",
        "Warrington",
        "Waverley",
        "Westgate",
        "Whare Flat",
        "Wingatui",
        "Woodhaugh"
      ],
      "Oamaru": [
        "Holmes Hill",
        "North End",
        "South Hill"
      ],
      "Queenstown-Lakes": [
        "Albert Town",
        "Arrow Junction",
        "Arrowtown",
        "Arthurs Point",
        "Boydtown",
        "Cardrona",
        "Closeburn",
        "Crown Terrace",
        "Fernhill",
        "Frankton",
        "Gibbston",
        "Glenorchy",
        "Goldfield Heights",
        "Hawea Flat",
        "Jacks Point",
        "Kelvin Peninsula",
        "Lake Hawea",
        "Lake Hayes Estate",
        "Lower Shotover",
        "Luggate",
        "Makarora",
        "Queenstown",
        "Queenstown East",
        "Queenstown Hill",
        "Sunshine Bay",
        "Wanaka"
      ],
      "Waitaki": [
        "Deborah",
        "Hampden",
        "Kakanui",
        "Kurow",
        "Moeraki",
        "Omarama",
        "Otematata",
        "Palmerston",
        "Richmond",
        "Taranui",
        "Waiareka",
        "Weston"
      ]
    },
    "South Canterbury": {
      "Fairlie": [
        "Allandale",
        "Ashwick Flat",
        "Cattle Valley",
        "Cricklewood",
        "Fairlie",
        "Kimbell",
        "Rockwood",
        "Winscombe"
      ],
      "Geraldine": [
        "Belfield",
        "Geraldine Downs",
        "Geraldine Flat",
        "Hilton",
        "Ohapi",
        "Pleasant Valley",
        "Rangitata",
        "Rangitata Island",
        "Speechleys Bridge"
      ],
      "Mackenzie": [
        "Burkes Pass",
        "Haldon Station",
        "Lake Mcgregor",
        "Lake Tekapo",
        "Lookout Point",
        "Twizel"
      ],
      "Temuka": [
        "Milford"
      ],
      "Timaru": [
        "Arundel",
        "Claremont",
        "Epworth",
        "Geraldine",
        "Gleniti",
        "Glenwood",
        "Grantlea",
        "Highfield",
        "Lyalldale",
        "Marchwiel",
        "Normanby",
        "Pareora",
        "Parkside",
        "Pleasant Point",
        "Port Timaru",
        "Redruth",
        "Salisbury",
        "Seaview",
        "Sherwood Downs",
        "Smithfield",
        "St Andrews",
        "Taiko",
        "Temuka",
        "Timaru",
        "Waimataitai",
        "Washdyke",
        "Watlington"
      ],
      "Waimate": [
        "Saint Andrews",
        "Waimate"
      ]
    },
    "Southland": {
      "Catlins": [
        "Roslyn Bush",
        "Waikawa Valley"
      ],
      "Gore": [
        "Charlton",
        "Croydon",
        "Croydon Bush",
        "Gore Central",
        "Howe",
        "Jacobs Town",
        "Knapdale",
        "Mataura",
        "Mcnab",
        "Otama",
        "Otamita",
        "Pahiwi",
        "Pukerau",
        "Upper Charlton",
        "Wayland",
        "Whiterigg"
      ],
      "Invercargill": [
        "Appleby",
        "Avenal",
        "Bluff",
        "Clifton",
        "Georgetown",
        "Gladstone",
        "Glengarry",
        "Grasmere",
        "Hargest",
        "Hawthorndale",
        "Heidelberg",
        "Invercargill City",
        "Kennington",
        "Kew",
        "Kingswell",
        "Lorneville",
        "Makarewa",
        "Mill Road",
        "Myross Bush",
        "Newfield",
        "Omaui",
        "Oreti Beach",
        "Otatara",
        "Rockdale",
        "Rosedale",
        "Strathern",
        "Tisbury",
        "Waikiwi",
        "Waverley",
        "Windsor",
        "Woodend"
      ],
      "Southland": [
        "Athol",
        "Avondale",
        "Bayswater",
        "Browns",
        "Centre Bush",
        "Colac Bay",
        "Dipton West",
        "Drummond",
        "Eastern Bush",
        "Edendale",
        "Garston",
        "Isla Bank",
        "Kingston",
        "Limehills",
        "Lumsden",
        "Manapouri",
        "Mandeville",
        "Mossburn",
        "Nightcaps",
        "Ohai",
        "Orepuki",
        "Otautau",
        "Riversdale",
        "Riverton",
        "Ryal Bush",
        "Stewart Island",
        "Tapanui",
        "Te Anau",
        "Thornbury",
        "Tokanui",
        "Tuatapere",
        "Waikaia",
        "Waikaka",
        "Waituna",
        "Wallacetown",
        "Woodlands",
        "Wyndham"
      ],
      "Winton": [
        "Forest Hill",
        "Gap Road",
        "Hokonui",
        "Kauana",
        "Lady Barkly",
        "Lochiel",
        "Otapiri",
        "Springhills",
        "Winton"
      ]
    },
    "Taranaki": {
      "New Plymouth": [
        "Bell Block",
        "Blagdon",
        "Brixton",
        "Brooklands",
        "Egmont Village",
        "Fitzroy",
        "Frankleigh Park",
        "Glen Avon",
        "Highlands Park",
        "Hillsborough",
        "Hurdon",
        "Hurworth",
        "Inglewood",
        "Lepperton",
        "Lynmouth",
        "Mangorei",
        "Marfell",
        "Merrilands",
        "Mokau",
        "Moturoa",
        "New Plymouth City",
        "Oakura",
        "Okato",
        "Omata",
        "Onaero",
        "Royal Heights",
        "Spotswood",
        "Strandon",
        "Tariki",
        "Tarurutangi",
        "Tikorangi",
        "Urenui",
        "Vogeltown",
        "Waitara",
        "Waiwhakaiho",
        "Welbourn",
        "Westown",
        "Whalers Gate"
      ],
      "South Taranaki": [
        "Alton",
        "Eltham",
        "Hawera",
        "Kaponga",
        "Manaia",
        "Mangatoki",
        "Normanby",
        "Okaiawa",
        "Opunake",
        "Patea",
        "Pungarehu",
        "Rahotu",
        "Tokaora",
        "Waitotara",
        "Warea",
        "Waverley",
        "Whareroa"
      ],
      "Stratford": [
        "Midhurst",
        "Stratford",
        "Stratford East",
        "Stratford West",
        "Toko"
      ]
    },
    "Waikato": {
      "Hamilton": [
        "Alandale",
        "Bader",
        "Beerescourt",
        "Callum Brae",
        "Chartwell",
        "Chedworth Park",
        "Claudelands",
        "Deanwell",
        "Dinsdale",
        "Enderley",
        "Fairfield",
        "Fairview Downs",
        "Fitzroy",
        "Flagstaff",
        "Forest Lake",
        "Frankton",
        "Glenview",
        "Hamilton City",
        "Hamilton East",
        "Hamilton North",
        "Hamilton West",
        "Harrowfield",
        "Hillcrest",
        "Horsham Downs",
        "Livingstone",
        "Maeroa",
        "Melville",
        "Nawton",
        "Puketaha",
        "Pukete",
        "Queenwood",
        "Rotokauri",
        "Rototuna",
        "Ruakura",
        "Silverdale East",
        "Silverdale West",
        "Strathmore",
        "Tauwhare",
        "Te Rapa",
        "Temple View",
        "Western Heights",
        "Whitiora"
      ],
      "Hauraki": [
        "Kerepehi",
        "Netherton",
        "Ngatea",
        "Paeroa",
        "Turua",
        "Waihi",
        "Waihi East",
        "Waikino",
        "Waitakaruru",
        "Whiritoa"
      ],
      "Matamata-Piako": [
        "Buckland",
        "Mangateparu",
        "Matamata",
        "Okauia",
        "Patetonga",
        "Springdale",
        "Tahuna",
        "Te Aroha",
        "Te Poi",
        "Turangaomoana",
        "Waharoa",
        "Waihou",
        "Waitoa",
        "Walton"
      ],
      "Morrinsville": [
        "Kereone",
        "Morrinsville",
        "Motumaoho",
        "Tauhei",
        "Te Puninga"
      ],
      "Otorohanga": [
        "Kawhia",
        "Otorohanga"
      ],
      "South Waikato": [
        "Aotea",
        "Hodderville",
        "Kinleith",
        "Ngatira",
        "Paraonui",
        "Putarura",
        "Putaruru",
        "Strathmore",
        "Tirau",
        "Tokoroa Central",
        "Wiltsdown"
      ],
      "Taupo": [
        "Acacia Bay",
        "Arataki",
        "Hilltop",
        "Invergarry",
        "Kinloch",
        "Kuratau",
        "Mangakino",
        "Motuoapa",
        "Nukuhau",
        "Omori",
        "Oruanui",
        "Pukawa",
        "Rainbow Point",
        "Rangatira Park",
        "Richmond Heights",
        "Tauhara",
        "Taupo Central",
        "Te Rangiita",
        "Tongariro",
        "Turangi",
        "Waipahihi",
        "Wairakei",
        "Waitahanui",
        "Whakamaru",
        "Wharewaka"
      ],
      "Thames-Coromandel": [
        "Awaiti",
        "Cooks Beach",
        "Coroglen",
        "Coromandel",
        "Flaxmill Bay",
        "Hahei",
        "Hikutaia",
        "Hot Water Beach",
        "Kaimarama",
        "Kopu",
        "Kuaotunu Beach",
        "Little Bay",
        "Matarangi",
        "Matatoki",
        "Ngarimu Bay",
        "Onemana",
        "Opito",
        "Opoutere",
        "Pauanui",
        "Pauanui Beach",
        "Port Charles",
        "Puriri",
        "Simpsons Beach",
        "Tairua",
        "Tapu",
        "Tararu",
        "Te Kouma",
        "Te Mata",
        "Te Puru",
        "Thames",
        "Thornton Bay",
        "Totara",
        "Waihirere",
        "Waikawau",
        "Waiomu",
        "Waitawheta",
        "Whangamata",
        "Whangapoua",
        "Wharekaho Beach",
        "Whitianga"
      ],
      "Waikato": [
        "Eureka",
        "Glen Murray",
        "Gordonton",
        "Horotiu",
        "Huntly",
        "Kainui",
        "Matangi",
        "Meremere",
        "Miranda",
        "Newstead",
        "Ngaruawahia",
        "Ohinewai",
        "Oparau",
        "Raglan",
        "Rangiriri",
        "Rotongaro",
        "Rotowaro",
        "Tamahere",
        "Taupiri",
        "Te Kauwhata",
        "Te Kowhai",
        "Te Uku",
        "Whatawhata",
        "Whitikahu"
      ],
      "Waimate": [
        "Saint Andrews",
        "Silverdale"
      ],
      "Waipa": [
        "Cambridge",
        "Horahora",
        "Karamu",
        "Karapiro",
        "Kihikihi",
        "Leamington",
        "Ngahinapouri",
        "Ohaupo",
        "Pirongia",
        "Pukekura",
        "Te Awamutu",
        "Te Pahu",
        "Te Rore"
      ],
      "Waitomo": [
        "Awakino",
        "Piopio",
        "Te Kuiti"
      ]
    },
    "Wairarapa": {
      "Wairarapa": [
        "Bideford",
        "Carterton",
        "Castlepoint",
        "Dyerville",
        "Featherston",
        "Gladstone",
        "Greytown",
        "Lansdowne",
        "Martinborough",
        "Masterton",
        "Opaki",
        "Riversdale Beach",
        "Solway",
        "Tauweru",
        "Tinui",
        "Westmere"
      ]
    },
    "Wanganui": {
      "Ruapehu": [
        "National Park",
        "Ohakune",
        "Ohura",
        "Owhango",
        "Raetihi",
        "Taumarunui",
        "Waiouru"
      ],
      "Wanganui": [
        "Aramoho",
        "Bastia Hill",
        "Brunswick",
        "Castlecliff",
        "Durie Hill",
        "Fordell",
        "Gonville",
        "Kai Iwi",
        "Kaitoke",
        "Makirikiri",
        "Mangamahu",
        "Marybank",
        "Maxwell",
        "Mosston",
        "Okoia",
        "Otamatea",
        "Putiki",
        "Rapanui",
        "Saint Johns Hill",
        "Springvale",
        "Tawhero",
        "Upokongaro",
        "Wanganui",
        "Wanganui City",
        "Wanganui East",
        "Westmere",
        "Whanganui",
        "Whanganui City"
      ]
    },
    "Wellington": {
      "Kapiti Coast": [
        "Crown Hill",
        "Makerua",
        "Mangahao",
        "Maungakotukutuku",
        "Nikau Valley",
        "Otaihanga",
        "Otaki",
        "Otaki Beach",
        "Otaki Forks",
        "Paekakariki",
        "Paraparaumu",
        "Paraparaumu Beach",
        "Peka Peka",
        "Raumati Beach",
        "Raumati South",
        "Te Horo",
        "Waikanae",
        "Waikanae Beach",
        "Waikawa Beach"
      ],
      "Lower Hutt": [
        "Alicetown",
        "Avalon",
        "Belmont",
        "Boulcott",
        "Days Bay",
        "Eastbourne",
        "Epuni",
        "Fairfield",
        "Gracefield",
        "Harbour View",
        "Haywards",
        "Holborn",
        "Kelson",
        "Korokoro",
        "Lower Hutt",
        "Lowry Bay",
        "Mahina Bay",
        "Manor Park",
        "Maungaraki",
        "Melling",
        "Moera",
        "Naenae",
        "Normandale",
        "Petone",
        "Pomare",
        "Rona Bay",
        "Seaview",
        "Stokes Valley",
        "Taita",
        "Tirohanga",
        "Wainuiomata",
        "Waiwhetu",
        "Waterloo",
        "Wingate",
        "Woburn"
      ],
      "Porirua": [
        "Aotea",
        "Ascot Park",
        "Camborne",
        "Cannons Creek",
        "Crown Hill",
        "Elsdon",
        "Judgeford",
        "Karehana Bay",
        "Mana",
        "Onepoto",
        "Papakowhai",
        "Paremata",
        "Pauatahanui",
        "Plimmerton",
        "Porirua",
        "Porirua East",
        "Pukerua Bay",
        "Ranui Heights",
        "Takapuwahia",
        "Titahi Bay",
        "Waitangirua",
        "Whitby"
      ],
      "Upper Hutt": [
        "Akatarawa",
        "Birchville",
        "Blue Mountains",
        "Brown Owl",
        "Clouston Park",
        "Ebdentown",
        "Elderslea",
        "Heretaunga",
        "Kingsley Heights",
        "Maidstone Park",
        "Mangaroa",
        "Maoribank",
        "Marua Palms",
        "Maymorn",
        "Moonshine",
        "Mt Marua",
        "Pinehaven",
        "Riverstone",
        "Riverstone Terraces",
        "Silverstream",
        "Te Marua",
        "The Plateau",
        "Timberlea",
        "Totara Park",
        "Trentham",
        "Upper Hutt",
        "Wallaceville",
        "Whitemans Valley"
      ],
      "Wellington": [
        "Aro Valley",
        "Berhampore",
        "Breaker Bay",
        "Broadmeadows",
        "Brooklyn",
        "Churton Park",
        "Crofton Downs",
        "Emerald Hill",
        "Evans Bay",
        "Glenside",
        "Grenada",
        "Grenada North",
        "Grenada Village",
        "Happy Valley",
        "Hataitai",
        "Highbury",
        "Horokiwi",
        "Houghton Bay",
        "Island Bay",
        "Johnsonville",
        "Kaiwharawhara",
        "Karaka Bays",
        "Karori",
        "Karori Mall",
        "Kelburn",
        "Kelvin Grove",
        "Khandallah",
        "Kilbirnie",
        "Kingston",
        "Kowhai Park",
        "Lyall Bay",
        "Makara-Ohariu",
        "Maupuia",
        "Melrose",
        "Miramar",
        "Moa Point",
        "Mornington",
        "Mount Cook",
        "Mount Crawford",
        "Mount Victoria",
        "Newlands",
        "Newtown",
        "Ngaio",
        "Ngauranga",
        "Northland",
        "Ohariu Valley",
        "Oriental Bay",
        "Owhiro Bay",
        "Paparangi",
        "Pipitea",
        "Rangoon Heights",
        "Raroa",
        "Rongotai",
        "Roseneath",
        "Seatoun",
        "Strathmore Park",
        "Tawa",
        "Te Aro",
        "Thorndon",
        "Vogeltown",
        "Wadestown",
        "Wellington Central",
        "Wilton",
        "Woodridge"
      ]
    },
    "West Coast": {
      "Buller": [
        "Carters Beach",
        "Charleston",
        "Fairdown",
        "Granity",
        "Hector",
        "Karamea",
        "Mount Albert",
        "Punakaiki",
        "Reefton",
        "Seddonville",
        "Springs Junction",
        "Waimangaroa",
        "Westport"
      ],
      "Grey": [
        "Ahaura",
        "Barrytown",
        "Blackball",
        "Blaketown",
        "Camerons",
        "Cobden",
        "Dobson",
        "Dunollie",
        "Gladstone",
        "Greymouth",
        "Ikamatua",
        "Karoro",
        "Moana",
        "Nelson Creek",
        "Ngahere",
        "Paroa",
        "Rapahoe",
        "Runanga",
        "Rutherglen",
        "South Beach",
        "Taylorville",
        "Totara Flat"
      ],
      "Westland": [
        "Bruce Bay",
        "Fox Glacier",
        "Franz Josef",
        "Harihari",
        "Hokitika",
        "Kaniere",
        "Kokatahi",
        "Kowhitirangi",
        "Kumara",
        "Ross",
        "Whataroa"
      ]
    }
  }
}
